### ISSUE TITLE
Unexpected error preventing me from joining my server!

### ISSUE THREAD

**Issue by badcrave** [maksim789456/DynamicSurroundingsFabric#23]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-12-22 19:59:01
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "org.orecruncher.dsurround.processing.scanner.RandomBlockEffectScanner.tick()" because "this.farEffects" is null
	at org.orecruncher.dsurround.processing.AreaBlockEffects.process(AreaBlockEffects.java:38)
	at org.orecruncher.dsurround.processing.Handlers.onTick(Handlers.java:109)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$cje000$onEndTick(class_310.java:15473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.orecruncher.dsurround.processing.AreaBlockEffects.process(AreaBlockEffects.java:38)
	at org.orecruncher.dsurround.processing.Handlers.onTick(Handlers.java:109)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$cje000$onEndTick(class_310.java:15473)

-- Affected level --
Details:
	All players: 1 total; [class_746['Starvexia'/54276, l='ClientLevel', x=-795.61, y=63.00, z=-567.66]]
	Chunk stats: 1024, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,113,-37), Section: (at 8,1,11 in 0,7,-3; chunk contains blocks 0,-64,-48 to 15,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 4202328 game time, 4477277 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, minecraft/supporteatinganimation, Everycomp Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4715408104 bytes (4496 MiB) / 8623489024 bytes (8224 MiB) up to 10804527104 bytes (10304 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8476
	Graphics card #2 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x249d
	Graphics card #2 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65399.42
	Virtual memory used (MB): 37632.18
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 964.98
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms8200M -Xmx10280M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.1
		adorn: Adorn 3.8.0+1.19.2
		advdebug: Advancements Debug 2.3.0
		amplifiednether: Amplified nether 1.2
		another_furniture: Another Furniture 2.1.2-1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		arcanus: Arcanus 1.30
		architectury: Architectury 6.4.62
		audaki_cart_engine: Audaki Cart Engine v2.0.0
		autoswitch: AutoSwitch 5.4.7
			autoswitch-api: AutoSwitch API 3.0.0
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		axesareweapons: Axes Are Weapons 1.6.0
		backslot: BackSlot 1.2.11
			amecsapi: Amecs API 1.3.6+mc22w17a
		backslotaddon: BackSlot Addon 1.0.10
		bakingmod: Baking Mod 1.0.5
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.5
		bedspreads: Bedspreads 6.0.0+1.19.2
		betteradvancements: Better Advancements 0.2.2.142
		betterbeaconplacement-fabric: Better Beacon Placement (Fabric) 2.1
		bettercombat: Better Combat 1.5.3+1.19
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.9.0
		bigbeacons: Big Beacons 1.2.6
		bookshelf: Bookshelf 16.2.16
		bottled_allays: BottledAllays 1.1.0
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cacao: Croptopia's Chocolaterie 1.2
		campanion: Campanion 4.1.2+fabric
		campchair: Camp Chair 1.0.2
		campsite_structures: Campsite Structures 1.0.2
		camsbackpacks: Cammie's Wearable Backpacks 2.13
		candymod: Candy Mod 1.0.3
		chisel: Chisel Refabricated 1.4.5
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		collective-fabric: Collective (Fabric) 5.22
			fiber: fiber 0.23.0-2
		combatroll: Combat Roll 1.1.1+1.19
		consistency_plus: Consistency Plus 0.5.1+1.19.2
			stonecutter_recipe_tags: Stonecutter Recipe Tags 4.0.0+1.19.9b8d04c.fabric
		controlling: Controlling For Fabric 10.0+7
		couplings: Couplings 1.9.1+1.19
		cpm: Customizable Player Models 0.6.1a
		crafttweaker: CraftTweaker 10.0.23
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		croptopia: Croptopia 2.1.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		doodads: Doodads 0.1.2-1.19.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.5_1
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dynamiccrosshair: Dynamic Crosshair 4.0+1.19.2
		dynamiccrosshaircompat: Dynamic Crosshair Compat 2.0+1.19.2
		dynmus: Dynamic Music 1.5.1
		ears: Ears 1.4.6
		eatinganimationid: Eating Animation 1.9
		ecologics: Ecologics 2.1.11
		endereyes: EnderEyes 1.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		everycomp: Every Compat 1.19.2-2.1.6
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.4
		expandedstorage: Expanded Storage 8.1.0-beta.3
		explorations: Explorations 1.19.2-1.3
		explorify-fabric: Explorify 1.19-1.3.0
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11
		fallingtree: FallingTree 3.10.0
		fastback: FastBack 0.7.4+1.19.2
			com_googlecode_javaewah_javaewah: JavaEWAH 1.1.13
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			net_i2p_crypto_eddsa: eddsa 0.3.0
			org_apache_sshd_sshd-common: sshd-common 2.8.0
			org_apache_sshd_sshd-core: sshd-core 2.8.0
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.2.0.202206071550-r
			org_eclipse_jgit_org_eclipse_jgit_ssh_apache: org.eclipse.jgit.ssh.apache 6.2.0.202206071550-r
			packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		fastload: Fast Load 2.4.4
		faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.2
		ferritecore: FerriteCore 5.0.3
		fldf: Fast Leaf Decay 1.0.0
		followersteleporttoo-fabric: Followers Teleport Too (Fabric) 1.2
		forgeconfigapiport: Forge Config API Port 4.2.9
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		fruit_snacks: Fruit Snacks 1.0.0
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		givemehat: Give Me Hats! 2.5.0
		glassdoor: Glass Doors 3.1.0-beta.1+1.19
		goldenberry: Golden Berry Mod 1.0.1
		gravestones: Gravestones v1.13
		harvestwithease: Harvest with ease 4.0.0.3
		hatlist: Hat List 1.3
		headindex: Head Index 1.0.9
		here-be-no-dragons: Here be no Dragons! 1.0.0
		holdthatchunk: Hold That Chunk 2.0.1
		htm: Hey That's Mine 1.1.6
			common-protection-api: Common Protection API 1.0.0
			server_translations_api: Server Translations API 1.4.18+1.19.2
		iceberg: Iceberg 1.0.46
		imst: Immersive structures 2.0.6
		indium: Indium 1.0.9+mc1.19.2
		ingredient-extension-api: Ingredient Extension API 3.0.6
		interactic: Interactic 0.1.11+1.19
		inventoryessentials: Inventory Essentials 5.0.0
		iris: Iris 1.4.5
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		jade: Jade 8.6.3
		jadeaddons: Jade Addons 3.0.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.5.0.296
		justmobheads-fabric: Just Mob Heads (Fabric) 6.2
		justplayerheads-fabric: Just Player Heads (Fabric) 2.5
		keepheadnames: Keep Head Names 1.5.1
		kibe: Kibe 1.9.10-BETA+1.19
			playerabilitylib: Pal 1.6.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazy-language-loader: lazy-language-loader 0.3.1
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.3.3
		lightstones: Lightstones 1.7.1
		limitedchunks: Limited Chunkloading Mod 1.19.2-2.6
		lithium: Lithium 0.10.4
		logical_zoom: Logical Zoom 0.0.17
		lootr: Lootr 0.4.25.64
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcwbridges: Macaw's Bridges 1.0.6
		mcwdoors: Macaw's Doors 1.0.7
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.8
		mcwwindows: Macaw's Windows 2.1.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.1.19
		morenugget: More Nuggets 1.0.1-1.19-1.19.2
		mousetweaks: Mouse Tweaks 2.22
		notenoughanimations: NotEnoughAnimations 1.6.2
		numismatic-overhaul: Numismatic Overhaul 0.2.6+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			stacc: Stacc 1.3.3
		numismaticclaim: Numismatic Claim 1.0.4
		openpartiesandclaims: Open Parties and Claims 0.16.5
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		paintings: Paintings++ 10.2.4.0
		paradise_lost: Paradise Lost 2.0.2-beta+1.19.2
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			satin: Satin 1.8.0
		passableleaves: PassableLeaves 1.3.5
		patchouli: Patchouli 1.19.2-77-FABRIC
		pearlad: Ender Pearl AD 0.0.2
		player-animator: Player Animator 0.4.0
		playerpronouns: Player Pronouns 1.5.0+1.19
			more_codecs: More Codecs 0.2.2+1.18
		presencefootsteps: Presence Footsteps 1.6.3
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		quickshulker: Quick Shulker 1.3.9-1.19
			kyrptconfig: Kyrpt Config 1.4.16-1.19
			shulkerutils: shulkerutils 1.0.4-1.19
		redstonebits: Redstone Bits 1.8.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		rottencreatures: Rotten Creatures 1.0.1
		sandwichmod: Sandwich Mod 2.0.5
		secretrooms: Secret Rooms 1.3.2+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		shouldersurfing: Shoulder Surfing Reloaded 2.2.16
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		snorkelmod: Snorkel Mod 1.0.4
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 2.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.14+mc1.19.2-build.80
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spiceoffabric: Spice of Fabric 1.6.0-beta.2+1.19.2
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		sspb: Sodium Shadowy Path Blocks 3.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		symbol-chat: Symbol Chat 1.19.2-0.5.1
		terrablender: TerraBlender 2.0.1.130
		terralith: Terralith 2.3
		tiered: Tiered 1.2.1
		tooltipfix: ToolTip Fix 1.1.1-1.19
		transparent: Transparent 5.1.2
		trapexpansion: Trap Expansion 1.1.0
		traverse: Traverse 6.0.6
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.2.0
			terraform-config-api-v1: Terraform Config API (v1) 4.2.0
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.2.0
			terraform-tree-api-v1: Terraform Tree API (v1) 4.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
			traverse-client: Traverse: Client 6.0.6
			traverse-common: Traverse: Common 6.0.6
			traverse-worldgen: Traverse: World Generation 6.0.6
		trinkets: Trinkets 3.4.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		twilightforest: The Twilight Forest 4.2.333
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.642+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.642+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.642+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.642+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.642+1.19.2
				porting_lib_models: Porting Lib Models 2.1.642+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.642+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.642+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.642+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.642+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.642+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.642+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.642+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.642+1.19.2
						porting_lib_common: Porting Lib Common 2.1.642+1.19.2
		universal_shops: Universal Shops 1.0.1+1.19.2
			common-economy-api: Common Economy API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			polymer: Polymer (Core) 0.2.19+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			sgui: sgui 1.1.5+1.19.1
		variantcraftingtables: Variant Crafting Tables 3.2.9
		vcinteraction: Voice Chat Interaction 1.19.2-1.0.3
		voicechat: Simple Voice Chat 1.19.2-2.3.23
		walljump-fabric: Wall-Jump! UNOFFICIAL 1.6.1b
		waystone_towers: Waystone Towers 1.0.8
		whydoesmyglasssoundlikethat: Why Does My Glass Sound Like That 1.0.1
		wooltostring: Wool-to-String 1.0.4
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: Custom (+38 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1280x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default, minecraft/supporteatinganimation, Everycomp Generated Pack
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by OreCruncher** [comment]
Figured I would chime in on this.  I suspect that the onConnect() logic is firing on a thread other than the client thread, whereas process is running on the client thread.  Basically a race condition.  I need to figure out how to unravel it.
